version: "3.8"
services:
  webapp:
    build: .
    volumes:
      - "./poetry.lock:/code/poetry.lock"
      - "./pyproject.toml:/code/pyproject.toml"
      - "./app.py:/code/app.py"
    ports:
      - "8000:8000"
